# Mongo db pod with volumes(HostPath)
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongodbrs
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
     metadata:
       name: mongodbpod
       labels:
         app: mongodb
     spec:
       volumes:
       - name: hostpathvol
         hostPath:
           path: /tmp/mongodbbkp      
       containers:
       - name: mongodbcontainer
         image: mongo
         ports:
         - containerPort: 27017
        #  envFrom:
        #  - secretRef:
        #     name:  mongodb-password
         env:
          - name: MONGO_DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: mongo-configmap
                key: db-username
          - name: MONGO_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-password
                key: db-password
         volumeMounts:
         - name: hostpathvol
           mountPath: /data/db   
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017