apiVersion: v1
kind: Secret
metadata:
  name: mongodb-password
type: Opaque
stringData:
 # username: YWRtaW4=
  db-password: YWRtaW5AMTIz
# To create your password run the command below and change devdb@123 with your desired password
# #echo -n 'devdb@123' | base64